site_name: My Docs
theme:
  name: material
  features:
    - navigation.indexes

plugins:
  - blog:
      blog_toc: true
      post_date_format: yyyy MMM dd, HH:mm
      archive_date_format: MMMM yyyy
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  blog:
    show_time: true

nav:
  - Home: index.md
  - Blog: blog/index.md
