site_name: My Docs
theme:
  name: material

plugins:
  - search
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  blog:
    show_time: true

nav:
  - Home: index.md
  - Blog: blog/index.md
